name: 'Typescript Build'

on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Check out repository code
        uses: actions/checkout@v3

      - name: âš™ï¸ Build ts code
        run: yarn tsbuild

      - name: â¬‡ï¸ Commit and push changes
        run: |
          git config --global user.name "ğŸ¤– Github actions"
          git config --glboal user.email "***REMOVED***"

          git add -A
          git commit -m "build: build websockets server's typescript code"
          git push
